import type { SidebarConfig } from '@vuepress/theme-default';
import { commandCategories } from './command_categories';

export const sidebarFr: SidebarConfig = {
  '/fr/book/': [
    {
      text: 'Introduction',
      link: '/fr/book/README.md',
      collapsible: false,
    },
    {
      text: 'Installation',
      link: '/fr/book/installation.md',
      collapsible: false,
      children: ['/fr/book/default_shell.md'],
    },
    {
      text: 'Prise en main',
      link: '/fr/book/getting_started.md',
      collapsible: false,
      children: [
        '/fr/book/quick_tour.md',
        '/fr/book/moving_around.md',
        '/fr/book/thinking_in_nu.md',
        '/fr/book/cheat_sheet.md',
      ],
    },
    {
      text: 'Fondamentaux de Nu',
      link: '/fr/book/nu_fundamentals.md',
      collapsible: false,
      children: [
        '/fr/book/types_of_data.md',
        '/fr/book/loading_data.md',
        '/fr/book/pipelines.md',
        '/fr/book/working_with_strings.md',
        '/fr/book/working_with_lists.md',
        '/fr/book/working_with_records.md',
        '/fr/book/working_with_tables.md',
        '/fr/book/navigating_structured_data.md',
        '/fr/book/special_variables.md',
      ],
    },
    {
      text: 'Programmer en Nu',
      link: '/fr/book/programming_in_nu.md',
      collapsible: false,
      children: [
        '/fr/book/custom_commands.md',
        '/fr/book/aliases.md',
        '/fr/book/operators.md',
        '/fr/book/variables.md',
        '/fr/book/control_flow.md',
        '/fr/book/scripts.md',
        {
          text: 'Modules',
          link: '/fr/book/modules.md',
          collapsible: false,
          children: [
            '/fr/book/modules/using_modules.md',
            '/fr/book/modules/creating_modules.md',
          ],
        },
        '/fr/book/overlays.md',
        '/fr/book/sorting.md',
        '/fr/book/testing.md',
        '/fr/book/style_guide.md',
      ],
    },
    {
      text: 'Nu en tant que Shell',
      link: '/fr/book/nu_as_a_shell.md',
      collapsible: false,
      children: [
        '/fr/book/configuration.md',
        '/fr/book/environment.md',
        '/fr/book/stdout_stderr_exit_codes.md',
        '/fr/book/running_externals.md',
        '/fr/book/3rdpartyprompts.md',
        '/fr/book/directory_stack.md',
        '/fr/book/line_editor.md',
        '/fr/book/custom_completions.md',
        '/fr/book/externs.md',
        '/fr/book/coloring_and_theming.md',
        '/fr/book/hooks.md',
        '/fr/book/background_jobs.md',
      ],
    },
    {
      text: 'Venir à Nu',
      link: '/fr/book/coming_to_nu.md',
      collapsible: false,
      children: [
        '/fr/book/coming_from_bash.md',
        '/fr/book/coming_from_cmd.md',
        '/fr/book/coming_from_powershell.md',
        '/fr/book/nushell_map.md',
        '/fr/book/nushell_map_imperative.md',
        '/fr/book/nushell_map_functional.md',
        '/fr/book/nushell_operator_map.md',
      ],
    },
    {
      text: 'Notes de conception',
      link: '/fr/book/design_notes.md',
      collapsible: false,
      children: ['/fr/book/how_nushell_code_gets_run.md'],
    },
    {
      text: 'Avancé',
      link: '/fr/book/advanced.md',
      collapsible: false,
      children: [
        '/fr/book/standard_library.md',
        '/fr/book/dataframes.md',
        '/fr/book/metadata.md',
        '/fr/book/creating_errors.md',
        '/fr/book/parallelism.md',
        '/fr/book/plugins.md',
        '/fr/book/explore.md',
      ],
    },
  ],
  '/blog/': false,
};
